name: say hello

on:
  push:
    branches:
      - main

jobs:
  hello_world:
    runs-on: ubuntu-18.04
    steps:
    # Es como un array de los pasos que queremos que tenga
      - name: Echo the message
        run: |
          echo "Hola Midu!"
      - name: Dime la fecha
        run: date
    #A este paso no le di un nombre asi que el nombre sera igual al comando
      - run: ls -l
