name: Deployment Pipeline

on: 
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
      # OPTIMIZA LA INTEGRACION
        run: npm install --no-audit --no-fund --no-optional
      - name: Linter
        run: npm run eslint
      - name: Build
        run: npm run build 
      - name: Tests
        run: npm test

